//@top-level false
typedef struct host_info {
  string hostname;
  string sysname;
  string release_name;
  string machine;
} host_info_t;

//@top-level false
typedef struct load_average {
  double load_one;
  double load_five;
  double load_fifteen;
} load_average_t;

struct sysmon_status {
  host_info_t host; //@key
  double cpu_temp;
  load_average_t lavg;
  double cpu_user;
  double cpu_system;
  double cpu_idle;
  double mem_total;
  double mem_used;
  double mem_free;
  double swap_total;
  double swap_used;
  double swap_free;
};
