//@top-level false
typedef struct host_info {
  string hostname;
  string sysname;
  string release_name;
  string machine;
} host_info_t;

struct filesystem {
  host_info_t host; //@key
  string name; //@key
  string mountdir;
  long total;
  long used;
  long free;
  double used_per;
  double free_per;
  long write;
  long read;
};
